add autoshutdown tags to vm
hmcts/bastion pull request #106
Opened 2024-08-09 14:45 UTC by NickAzureDevops

### Jira link (https://tools.hmcts.net/jira/browse/DTSPO-18289)

add auto shutdown tag to bastion sbox and nonprod 

### Change description ###

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-08-09 14:59 UTC, NickAzureDevops commented
Pipeline run: https://dev.azure.com/hmcts/PlatformOperations/_build/results?buildId=629208&view=logs&j=87de6e83-4483-545f-5ee4-dd646a473fc0&t=9f07a130-add3-5319-3995-dd3dcc1a42ca&l=192

2024-08-12 10:20 UTC, bancey requested changes

2024-08-12 10:20 UTC, bancey commented on terraform/environment/sbox/21-bastion.tf
> +  common_tags       = merge(var.common_tags, local.auto_shutdown_common_tags)
var.common_tags here is an empty map, this should reference a call to the common tags module

2024-08-12 10:20 UTC, bancey commented on terraform/environment/nonprod/21-bastion.tf
> +  common_tags       = merge(var.common_tags, local.auto_shutdown_common_tags)
var.common_tags here is an empty map, this should reference a call to the common tags module

2024-08-13 13:51 UTC, NickAzureDevops commented
it is all fixed now. found out the tags were in the tag module but just set as false for auto shutdown

2024-08-13 13:54 UTC, NickAzureDevops commented
Run https://dev.azure.com/hmcts/PlatformOperations/_build/results?buildId=631308&view=logs&j=87de6e83-4483-545f-5ee4-dd646a473fc0&t=9f07a130-add3-5319-3995-dd3dcc1a42ca

2024-08-13 14:45 UTC, bancey approved these changes

2024-08-13 15:02 UTC, merged